version: '3.8'
# lancer avec : docker compose -f docker-compose.dev.yml --env-file .env up -d
services:
  backend:
    container_name: backend
    build:
      context: ./docker/
      dockerfile: Dockerfile-jdk
    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
  db:
    container_name: mongodb44
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_ROOT_DATABASE: "${MONGO_ROOT_DATABASE}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      # seeding scripts
      # - ./mongo-entrypoint/init.js:/docker-entrypoint-initdb.d/init.js
      # named volumes
      - ./${MONGO_DIRECTORY_DATABASE}:/data/db
